In [93]:
import pandas as pd

In [94]:
df = pd.read_csv("netflix_titles.csv")
df.info()
df.head()
display(df.describe(include="all").T)

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
show_id,8807,8807,s1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type,8807,2,Movie,6131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,8807,8807,Dick Johnson Is Dead,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
director,6173,4528,Rajiv Chilaka,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cast,7982,7692,David Attenborough,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,7976,748,United States,2818,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_added,8797,1767,"January 1, 2020",109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_year,8807.0,NaN,NaN,NaN,2014.180198,8.819312,1925.0,2013.0,2017.0,2019.0,2021.0
rating,8803,17,TV-MA,3207,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,8804,220,1 Season,1793,NaN,NaN,NaN,NaN,NaN,NaN,NaN
listed_in,8807,514,"Dramas, International Movies",362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,8807,8775,"Paranormal activity at a lush, abandoned prope...",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
# df.dropna(inplace=True)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [96]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

display(missing.sort_values("Missing_Percentage", ascending=False))

              Missing_Count  Missing_Percentage
director               2634               29.91
country                 831                9.44
cast                    825                9.37
date_added               10                0.11
rating                    4                0.05
duration                  3                0.03
show_id                   0                0.00
type                      0                0.00
title                     0                0.00
release_year              0                0.00
listed_in                 0                0.00
description               0                0.00

In [97]:
print(df.shape)
collumns_to_fill = [
    "director",
    "cast",
    "country",
    "rating",
    "listed_in",
    "description"
]
for col in collumns_to_fill:
    df[col] = df[col].fillna("Unknown")
df

(8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [98]:
df["date_added"] = pd.to_datetime(
    df["date_added"].str.strip(),
    errors="coerce"
)

print(df["date_added"].dtype)

datetime64[us]

In [99]:
duration_parts = (
    df["duration"]
    .astype("string")
    .str.strip()
    .str.extract(r"^(\d+)\s*(min|Season|Seasons)$", flags=0)
)

df["duration_value"] = pd.to_numeric(
    duration_parts[0],
    errors="coerce"
).astype("Int64")

df["duration_unit"] = duration_parts[1].replace({
    "Season": "Seasons"
})


display(df[["title", "duration", "duration_value", "duration_unit"]].head(10))

                              title   duration  duration_value duration_unit
0              Dick Johnson Is Dead     90 min              90           min
1                     Blood & Water  2 Seasons               2       Seasons
2                         Ganglands   1 Season               1       Seasons
3             Jailbirds New Orleans   1 Season               1       Seasons
4                      Kota Factory  2 Seasons               2       Seasons
5                     Midnight Mass   1 Season               1       Seasons
6  My Little Pony: A New Generation     91 min              91           min
7                           Sankofa    125 min             125           min
8     The Great British Baking Show  9 Seasons               9       Seasons
9                      The Starling    104 min             104           min

In [100]:
print("Exact duplicate rows:", df.duplicated().sum())

print("Duplicated show IDs:", df["show_id"].duplicated().sum())

Exact duplicate rows: 0
Duplicated show IDs: 0

In [101]:
# Check data types
df.info()

# Check missing values again
display(
    df.isnull().sum()
    .sort_values(ascending=False)
)

# Check date type
print("Date type:", df["date_added"].dtype)

# Check the duration columns
display(df[[
    "title",
    "type",
    "duration",
    "duration_value",
    "duration_unit"
]].head(10))

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8807 non-null   str
 1   type            8807 non-null   str
 2   title           8807 non-null   str
 3   director        8807 non-null   str
 4   cast            8807 non-null   str
 5   country         8807 non-null   str
 6   date_added      8797 non-null   datetime64[us]
 7   release_year    8807 non-null   int64
 8   rating          8807 non-null   str
 9   duration        8804 non-null   str
 10  listed_in       8807 non-null   str
 11  description     8807 non-null   str
 12  duration_value  8804 non-null   Int64
 13  duration_unit   8804 non-null   string
dtypes: Int64(1), datetime64[us](1), int64(1), str(10), string(1)
memory usage: 3.9 MB

date_added        10
duration           3
duration_unit      3
duration_value     3
show_id            0
type               0
country            0
cast               0
director           0
title              0
rating             0
release_year       0
description        0
listed_in          0
dtype: int64

Date type: datetime64[us]

,title,type,duration,duration_value,duration_unit
0,Dick Johnson Is Dead,Movie,90 min,90,min
1,Blood & Water,TV Show,2 Seasons,2,Seasons
2,Ganglands,TV Show,1 Season,1,Seasons
3,Jailbirds New Orleans,TV Show,1 Season,1,Seasons
4,Kota Factory,TV Show,2 Seasons,2,Seasons
5,Midnight Mass,TV Show,1 Season,1,Seasons
6,My Little Pony: A New Generation,Movie,91 min,91,min
7,Sankofa,Movie,125 min,125,min
8,The Great British Baking Show,TV Show,9 Seasons,9,Seasons
9,The Starling,Movie,104 min,104,min

In [102]:
df.to_csv(
    "netflix_titles_cleaned.csv",
    index=False,
    encoding="utf-8"
)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.